src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;



/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class , inversedBy="new")
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo_eng;

    /**
     * @ORM\Column(type="text")
     */
    private $contenido_esp;

    /**
     * @ORM\Column(type="text")
     */
    private $contenido_eng;
    
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $banner;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="banner")
     * @var File
     */
    private $bannerFile;
    
    
    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $updatedAt;
    
    /**
     * @ORM\Column(name="created", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $destacado;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $podcast;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $description_eng;

    /**
     * @ORM\Column(type="string", length=255 )
     */
    private $url;
    
    
     public function __toString() {
        return $this->name;
    }

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->updatedAt = new \DateTime();
        $this->fecha= new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addNew($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $this->categories->removeElement($category);
            $category->removeNew($this);
        }

        return $this;
    }

    public function getTituloEsp(): ?string
    {
        return $this->titulo_esp;
    }

    public function setTituloEsp(string $titulo_esp): self
    {
        $this->titulo_esp = $titulo_esp;

        return $this;
    }

    public function getTituloEng(): ?string
    {
        return $this->titulo_eng;
    }

    public function setTituloEng(string $titulo_eng): self
    {
        $this->titulo_eng = $titulo_eng;

        return $this;
    }

    public function getContenidoEsp(): ?string
    {
        return $this->contenido_esp;
    }

    public function setContenidoEsp(string $contenido_esp): self
    {
        $this->contenido_esp = $contenido_esp;

        return $this;
    }

    public function getContenidoEng(): ?string
    {
        return $this->contenido_eng;
    }

    public function setContenidoEng(string $contenido_eng): self
    {
        $this->contenido_eng = $contenido_eng;

        return $this;
    }
    
    
    
     /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }
    
    
     /**
     * @return mixed
     */
    public function getBannerFile()
    {
        return $this->bannerFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setBannerFile($bannerFile): void
    {
        $this->bannerFile = $bannerFile;

        if ($bannerFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setBanner($banner)
    {
        $this->banner = $banner;
    }

    public function getBanner()
    {
        return $this->banner;
    }
    
    

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdated()
    {
        return $this->updated;
    }
    
        public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(?\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): self
    {
        $this->destacado = $destacado;

        return $this;
    }

    public function getPodcast(): ?string
    {
        return $this->podcast;
    }

    public function setPodcast(?string $podcast): self
    {
        $this->podcast = $podcast;

        return $this;
    }

    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self
    {
        $this->spotify = $spotify;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDescriptionEng(): ?string
    {
        return $this->description_eng;
    }

    public function setDescriptionEng(string $description_eng): self
    {
        $this->description_eng = $description_eng;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
    
    
}

src/Controller/PostViewController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Entity\Category;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostViewController extends AbstractController {

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(string $name = null, EntityManagerInterface $entityManager) {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/noticia/{url}", name="post_view")
     */
    public function reedem(News $news) {
        $date = $news->getFecha();
        $category = $this->entityManager->getRepository(Category::class)->findAll();
        $next = $this->entityManager->getRepository(News::class)->findByNext($date);
        $previous = $this->entityManager->getRepository(News::class)->findByPrevious($date);
        $posts = $this->entityManager->getRepository(News::class)->findBy(
                array(), array('fecha' => 'DESC'), 3
        );

        return $this->render('post_view/index.html.twig', [
                    'controller_name' => 'PostViewController',
                    "post" => $news,
                    "posts" => $posts,
                    "previous" => $previous,
                    "next" => $next,
                    "category" => $category,
        ]);
    }

    /**
     * @Route("/categoria/{url}", name="category_view")
     */
    public function category(Category $category) {


        return $this->render('blog/category.html.twig', [
                    'name' => $category,
                    "posts" => $category->getNew(),
        ]);
    }

}

templates/post_view/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}<title>Scalahed - Higher Education</title>{% endblock %}

{% block body %}
    <section class="new-wrap m-t-interior  m-md-t-10">
        <div class="container">
            <div class="row">
                <div class="col-12 offset-1 offset-md-0 return  d-none d-sm-block ">
                    <a href="{{ path('blog')}}" class="d-flex align-items-center text-primary ">
                        <img src="{{ asset('build/images/template/regresa.png') }}" alt="" class="img-fluid m-r-1"/>
                        {% trans %}
                            REGRESAR
                        {% endtrans %}
                    </a>
                </div>

                <div class="col-md-24 offset-md-0 col-22 offset-1  text-center m-t-1 m-b-3 m-md-b-0 ">
                    <img src="{{ vich_uploader_asset(post) }}" class='w-100 h-auto '/>

                </div>
                <div class="col-md-16 offset-md-0 col-22 offset-1 m-t-3 m-b-1 ">
                    <span class="article" style="background: #{{ post.categories[0].color is null ? '':post.categories[0].color }}">
                        <a href="{{ path('category_view',{url: post.categories[0].url}) }}" class="">
                            {{ app.request.locale == 'es' ? post.categories[0].nameEsp: post.categories[0].name }}
                        </a>
                    </span>
                    <h2 class="text-dark text-md-start   m-t-5 m-md-t-1">
                        {% if app.request.locale == 'es' %}
                            {{post.tituloEsp}}
                        {% else %}
                            {{post.tituloEng}}
                        {% endif %}

                    </h2>
                    <hr class="d-block d-sm-none m-t-2">
                    <p class="text-primary m-t-2">
                        {{post.fecha|date('d-m-Y')}}
                    </p>
                </div>
                <div class="col-md-16 offset-md-0 col-22 offset-1 p-r-3 ">
                    <section class="content-wrap ">
                        {% if app.request.locale == 'es' %}
                            {{post.contenidoEsp|raw}}
                        {% else %}
                            {{post.contenidoEng|raw}}
                        {% endif %}
                    </section>
                    <section class="second-wrap m-b-5 d-flex align-items-center d-none d-sm-block">
                        <span class="m-r-1">Temas:</span>
                        {% for categorie in post.categories[1:] %}
                            <span class="article" style="background: #{{ categorie.color is null ? '':categorie.color }}">
                                <a href="{{ path('category_view',{url: categorie.url}) }}" class="">
                                    {{ app.request.locale == 'es' ? categorie.nameEsp: categorie.name }}
                                </a>
                            </span>
                        {% endfor %}
                    </section>
                    <section class=" m-y-4 d-block d-sm-none timeline">
                        <div class="row">
                            <div class="col-12">
                                {% if previous is not empty %}
                                    <a href="{{ path('post_view',{url: previous[0].url}) }}" class="text-primary m-b-1">
                                        {% trans %}
                                            ANTERIOR
                                        {% endtrans %}
                                    </a>
                                {%endif%}


                            </div>
                            <div class="col-12 text-end">
                                {% if next is not empty %}
                                    <a href="{{ path('post_view',{url: next[0].url}) }}" class="text-primary m-b-1">
                                        {% trans %}
                                            SIGUIENTE
                                        {% endtrans %}
                                    </a>
                                {%endif%}
                            </div>
                        </div>

                    </section>
                </div>

                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-24">
                            <h4 class="m-t-3 m-l-3 m-md-l-0">
                                {% trans %}
                                    Última noticia
                                {% endtrans %}
                            </h4>
                        </div>
                        {% for post in posts %}
                            <div class="col-md-24 offset-md-0 col-22 offset-1 m-t-10 m-md-t-2">
                                <div class="row h-100">
                                    <div class="col-24 position-relative">
                                        <div class="container-new order-md-0 order-0">
                                            <a href="{{ path('post_view',{url: post.url}) }}" class="">
                                                <img src="{{ vich_uploader_asset(post) }}" class='img-fluid '/>
                                            </a>
                                        </div>
                                        <div class="container-categories m-md-t-2 m-y-5 order-md-1 order-1">
                                            <span class="article m-t-1" style="background: #{{ post.categories[0].color is null ? '':post.categories[0].color }}">
                                                <a href="{{ path('category_view',{url: post.categories[0].url}) }}" class="">
                                                    {{ app.request.locale == 'es' ? post.categories[0].nameEsp: post.categories[0].name }}
                                                </a>
                                            </span>
                                        </div>
                                        <h4 class=" title-new m-t-1 order-md-2 order-2">
                                            <a href="{{ path('post_view',{url: post.url}) }}" class="">
                                                {% if app.request.locale == 'es' %}
                                                    {{post.tituloEsp}}
                                                {% else %}
                                                    {{post.tituloEng}}
                                                {% endif %}
                                            </a>
                                        </h4>

                                        <hr class="d-block d-sm-none m-y-2 ">

                                        <p class="text-primary date-new">
                                            {{post.fecha|date('d-m-Y')}}
                                        </p>

                                    </div>

                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-24 offset-md-0 col-22 offset-1 m-t-10 m-md-t-2 list-category  m-y-5 m-md-y-0">

                            <h4 class=" m-t-2 m-md-b-1 m-b-4">
                                Categorías
                            </h4>

                            {% for item in category %}
                                <a href="{{ path('category_view',{url: item.url}) }}" class="">
                                    {{ app.request.locale == 'es' ? item.nameEsp: item.name }}
                                </a><br>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
            <section class=" d-none d-sm-block">
                <div class="row m-b-5 ">
                    <div class="col-md-8 col-12">
                        {% if previous is not empty %}
                            <a href="{{ path('post_view',{url: previous[0].url}) }}" class="text-primary m-b-1">
                                {% trans %}
                                    ANTERIOR
                                {% endtrans %}
                            </a>
                            <section class="d-none d-sm-block">
                                <div class="container-new">
                                    <a href="{{ path('post_view',{url: previous[0].url}) }}" class="">
                                        <img src="{{ vich_uploader_asset(previous[0]) }}" class='img-fluid '/>
                                    </a>
                                </div>
                                <div class="container-categories m-t-2">

                                    {% if previous[0] is defined %}
                                        {% set firstItem = previous[0].categories[0] %}
                                        <span class="article" style="background: #{{ firstItem.color is null ? '':firstItem.color }}">
                                            <a href="{{ path('category_view',{url: firstItem.url}) }}" class="">
                                                {{ app.request.locale == 'es' ? firstItem.nameEsp: firstItem.name }}
                                            </a>
                                        </span>
                                    {% endif %}



                                </div>
                                <h4 class=" title-new m-t-1">
                                    <a href="{{ path('post_view',{url: previous[0].url}) }}" class="">
                                        {% if app.request.locale == 'es' %}
                                            {{previous[0].tituloEsp}}
                                        {% else %}
                                            {{previous[0].tituloEng}}
                                        {% endif %}
                                    </a>
                                </h4>
                            </section>
                            {#<p class="text-primary date-new">
                                {{previous[0].fecha|date('d-m-Y')}}
                            </p>#}
                        {% endif %}
                    </div>
                    <div class="col-md-8 offset-md-7 col-12 ">
                        {% if next is not empty %}
                            <div class="w-100 text-end">
                                <a href="{{ path('post_view',{url: next[0].url}) }}" class="text-primary m-b-1">
                                    {% trans %}
                                        SIGUIENTE
                                    {% endtrans %}
                                </a>
                            </div>
                            <section class="d-none d-sm-block">
                                <div class="container-new">
                                    <a href="{{ path('post_view',{url: next[0].url}) }}" class="">
                                        <img src="{{ vich_uploader_asset(next[0]) }}" class='img-fluid '/>
                                    </a>
                                </div>
                                <div class="container-categories m-t-2">
                                    {% if next[0] is defined %}
                                        {% set firstItem = next[0].categories[0]%}
                                        <span class="article m-t-1" style="background: #{{ firstItem.color is null ? '':firstItem.color }}">
                                            <a href="{{ path('category_view',{url: firstItem.url}) }}" class="">
                                                {{ app.request.locale == 'es' ? firstItem.nameEsp: firstItem.name }}
                                            </a>
                                        </span>
                                    {% endif %}
                                </div>
                                <h4 class=" title-new m-t-1">
                                    <a href="{{ path('post_view',{url: next[0].url}) }}" class="">

                                        {% if app.request.locale == 'es' %}
                                            {{next[0].tituloEsp}}
                                        {% else %}
                                            {{next[0].tituloEng}}
                                        {% endif %}

                                    </a>
                                </h4>
                            </section>
                        {% endif %}
                    </div>
                </div>
            </section>
        </div>
    </section>


{% endblock %}

templates/post_view/post_list.html.twig
{% for post in posts %}

    <div class="col-md-12 offset-md-0 col-22 offset-1 m-t-10 m-md-t-3">
        <div class="row h-100">
            <div class="col-24 position-relative">
                <div class="container-categories">
                    <span class="article m-t-1" style="background: #{{ post.categories[0].color is null ? '':post.categories[0].color }}">
                        <a href="{{ path('category_view',{url: post.categories[0].url}) }}" class="">
                            {{ app.request.locale == 'es' ? post.categories[0].nameEsp: post.categories[0].name }}
                        </a>
                    </span>
                </div>

                <h4 class="m-t-7 m-md-t-0  title-new">
                    <a href="{{ path('post_view',{url: post.url}) }}" class="" onclick="gtag('event', 'Ir a Post', {'event_category': 'Posts','event_label': '{{post.tituloEsp}}'});">
                        {{ app.request.locale == 'es' ? post.tituloEsp: post.tituloEng }}
                    </a>
                </h4>
                <p class="description-new">
                    {{ app.request.locale == 'es' ? post.description: post.descriptionEng }}
                </p>
                <hr>
                <p class="text-primary date-new">
                    {{post.fecha|date('d-m-Y')}}
                </p>
                <div class="container-new">

                    <a href="{{ path('post_view',{url: post.url}) }}" class="" onclick="gtag('event', 'Ir a Post', {'event_category': 'Posts','event_label': '{{post.tituloEsp}}'});">
                        <img src="{{ vich_uploader_asset(post, 'imageFile') }}" class='img-fluid '/>
                    </a>
                </div>
            </div>

        </div>
    </div>

{% endfor %}