src/Entity/Coffee.php
<?php

namespace App\Entity;

use App\Repository\CoffeeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CoffeeRepository::class)
 */
class Coffee
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="title_esp")
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title_eng;

    /**
     * @ORM\Column(type="text")
     */
    private $description_esp;

    /**
     * @ORM\Column(type="text")
     */
    private $description_eng;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_eng;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getTitleEsp(): ?string
    {
        return $this->title_esp;
    }

    public function setTitleEsp(string $title_esp): self
    {
        $this->title_esp = $title_esp;

        return $this;
    }

    public function getTitleEng(): ?string
    {
        return $this->title_eng;
    }

    public function setTitleEng(string $title_eng): self
    {
        $this->title_eng = $title_eng;

        return $this;
    }

    public function getDescriptionEsp(): ?string
    {
        return $this->description_esp;
    }

    public function setDescriptionEsp(string $description_esp): self
    {
        $this->description_esp = $description_esp;

        return $this;
    }

    public function getDescriptionEng(): ?string
    {
        return $this->description_eng;
    }

    public function setDescriptionEng(string $description_eng): self
    {
        $this->description_eng = $description_eng;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCodeEsp(): ?string
    {
        return $this->code_esp;
    }

    public function setCodeEsp(string $code_esp): self
    {
        $this->code_esp = $code_esp;

        return $this;
    }

    public function getCodeEng(): ?string
    {
        return $this->code_eng;
    }

    public function setCodeEng(string $code_eng): self
    {
        $this->code_eng = $code_eng;

        return $this;
    }
}

src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;



/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class , inversedBy="new")
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo_eng;

    /**
     * @ORM\Column(type="text")
     */
    private $contenido_esp;

    /**
     * @ORM\Column(type="text")
     */
    private $contenido_eng;
    
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $banner;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="banner")
     * @var File
     */
    private $bannerFile;
    
    
    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $updatedAt;
    
    /**
     * @ORM\Column(name="created", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $destacado;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $podcast;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $description_eng;

    /**
     * @ORM\Column(type="string", length=255 )
     */
    private $url;
    
    
     public function __toString() {
        return $this->name;
    }

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->updatedAt = new \DateTime();
        $this->fecha= new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addNew($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $this->categories->removeElement($category);
            $category->removeNew($this);
        }

        return $this;
    }

    public function getTituloEsp(): ?string
    {
        return $this->titulo_esp;
    }

    public function setTituloEsp(string $titulo_esp): self
    {
        $this->titulo_esp = $titulo_esp;

        return $this;
    }

    public function getTituloEng(): ?string
    {
        return $this->titulo_eng;
    }

    public function setTituloEng(string $titulo_eng): self
    {
        $this->titulo_eng = $titulo_eng;

        return $this;
    }

    public function getContenidoEsp(): ?string
    {
        return $this->contenido_esp;
    }

    public function setContenidoEsp(string $contenido_esp): self
    {
        $this->contenido_esp = $contenido_esp;

        return $this;
    }

    public function getContenidoEng(): ?string
    {
        return $this->contenido_eng;
    }

    public function setContenidoEng(string $contenido_eng): self
    {
        $this->contenido_eng = $contenido_eng;

        return $this;
    }
    
    
    
     /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }
    
    
     /**
     * @return mixed
     */
    public function getBannerFile()
    {
        return $this->bannerFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setBannerFile($bannerFile): void
    {
        $this->bannerFile = $bannerFile;

        if ($bannerFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setBanner($banner)
    {
        $this->banner = $banner;
    }

    public function getBanner()
    {
        return $this->banner;
    }
    
    

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdated()
    {
        return $this->updated;
    }
    
        public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(?\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): self
    {
        $this->destacado = $destacado;

        return $this;
    }

    public function getPodcast(): ?string
    {
        return $this->podcast;
    }

    public function setPodcast(?string $podcast): self
    {
        $this->podcast = $podcast;

        return $this;
    }

    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self
    {
        $this->spotify = $spotify;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDescriptionEng(): ?string
    {
        return $this->description_eng;
    }

    public function setDescriptionEng(string $description_eng): self
    {
        $this->description_eng = $description_eng;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
    
    
}

src/Entity/PlayBook.php
<?php

namespace App\Entity;

use App\Repository\PlayBookRepository;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlayBookRepository::class)
 * @Vich\Uploadable
 */
class PlayBook
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_eng;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;
    
      /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $updatedAt;
    
    
    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreEsp(): ?string
    {
        return $this->nombre_esp;
    }

    public function setNombreEsp(string $nombre_esp): self
    {
        $this->nombre_esp = $nombre_esp;

        return $this;
    }

    public function getNombreEng(): ?string
    {
        return $this->nombre_eng;
    }

    public function setNombreEng(string $nombre_eng): self
    {
        $this->nombre_eng = $nombre_eng;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
    
       /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setImageFile($imageFile): void
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }
       public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdated()
    {
        return $this->updated;
    }
    
    
    
}

src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TeamRepository::class)
 * @Vich\Uploadable
 */
class Team
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description_eng;

    /**
     * @ORM\Column(type="text")
     */
    private $description_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $position;
    
    
     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="photo")
     * @var File
     */
    private $photoFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $positionEng;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;
    
    
    
     /**
     * @return mixed
     */
    public function getPhotoFile()
    {
        return $this->photoFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setPhotoFile($photoFile): void
    {
        $this->photoFile = $photoFile;

        if ($photoFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    public function getPhoto()
    {
        return $this->photo;
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescriptionEng(): ?string
    {
        return $this->description_eng;
    }

    public function setDescriptionEng(string $description_eng): self
    {
        $this->description_eng = $description_eng;

        return $this;
    }

    public function getDescriptionEsp(): ?string
    {
        return $this->description_esp;
    }

    public function setDescriptionEsp(string $description_esp): self
    {
        $this->description_esp = $description_esp;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPositionEng(): ?string
    {
        return $this->positionEng;
    }

    public function setPositionEng(?string $positionEng): self
    {
        $this->positionEng = $positionEng;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }
}

templates/blog/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}<title>Scalahed - Higher Education</title>{% endblock %}

{% block body %}


    <section class="news-wrap m-b-10">
        <div class="container" >
            <div class="row m-md-t-7 m-t-interior  m-b-1">
                <div class="col-md-24 offset-md-0 col-22 offset-1 m-t-15 m-md-t-0">
                    <h2 class="text-primary m-t-4 text-md-start">
                        {{ app.request.locale == 'es' ? name.nameEsp: name.name }}
                        
                    </h2>
                </div>
            </div>
            <div class="row border-top">
                {% include 'post_view/post_list.html.twig' %}
            </div>
        </div>

    </section>


{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}<title>Scalahed - Higher Education</title>{% endblock %}

{% block body %}
    <section class="news-wrap m-t-interior  m-md-t-10 blog_animate start_animation">
        <div class="container">
            <div class="row">
                <div class="col-md-20 offset-md-1 col-22 offset-1 start_animation">
                    <h4 class="text-primary  text-center a-opacity-t">
                        {% trans %}
                            Entérese de las últimas noticias sobre Scala y las tendencias del sector
                        {% endtrans %}
                    </h4>
                </div>
            </div>
            <section class="a-opacity a-b-1 start_animation" id="blog-1">
                <div class="row ">
                    {% include 'post_view/post_list.html.twig' %}
                </div>
            </section>
        </div>
        <div class="container-fluid">
            <div class="row bg-secondary m-t-10">
                <div class="col">
                    <div class="container">
                        <div class="row m-t-10 a-b-2" id="blog-2">
                            <div class="col-24 text-md-end text-center m-md-b-2 m-b-5 ">
                                <div class="sound a-opacity">
                                    <a href="https://podcasts.apple.com/mx/podcast/un-caf%C3%A9-con-scala/id1559656116" target="_blank" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Apple'});">
                                        <img src="{{ asset('build/images/template/apple.svg') }}" alt="" class="img-fluid"/>
                                    </a>
                                    <a href="https://open.spotify.com/show/5aBjupDK3LqCYmlCEvkBNz" target="_blank" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Spotify'});">
                                        <img src="{{ asset('build/images/template/spotify.svg') }}" alt="" class="img-fluid"/>
                                    </a>
                                    <a href="https://soundcloud.com/scalahed" target="_blank" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Soundcloud'});">
                                        <img src="{{ asset('build/images/template/sound.svg') }}" alt="" class="img-fluid"/>
                                    </a>
                                    <a href="https://www.youtube.com/channel/UCTso-90g7wyYSj7suVKfghQ" target="_blank" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Youtube'});">
                                        <img src="{{ asset('build/images/template/youtube.svg') }}" alt="" class="img-fluid"/>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-7 col-12 mx-auto m-y-4 m-md-y-0 a-opacity-l">
                                <img src="{{ asset('build/images/template/coffee.png') }}" alt="" class="img-fluid"/>
                            </div>
                            <div class="col-md-16 offset-md-1 a-opacity-r">
                                <h4 class="text-primary">
                                    {% trans %}
                                        Espacio abierto a líderes del sector educativo empresarial, académico y gubernamental para hablar de educación.
                                    {% endtrans %}
                                </h4>
                            </div>
                        </div>
                        <div class="row " id="blog-3">
                            <div class="col-20 mx-auto video-coffee a-b-3">
                                <div class="row slider-coffee m-t-5 a-opacity">
                                    {% for video in coffee %}
                                        <div class="col-md-20 mx-auto p-x-1">
                                            <div class="container-categories m-t-5 m-md-t-0">
                                                {% for categorie in video.categories %}
                                                    <span class="article" style="background: #{{ categorie.color is null ? '':categorie.color }}">
                                                        {{ app.request.locale == 'es' ? categorie.nameEsp: categorie.name }}
                                                    </span>
                                                {% endfor %}
                                            </div>
                                            <h4 class="m-t-7  m-t-md- title-new">
                                                {{ app.request.locale == 'es' ? video.titleEsp: video.titleEng }}
                                            </h4>
                                            <hr>
                                            <p class="text-primary date-new">
                                                {{video.date|date('d-m-Y')}}
                                            </p>
                                            <div class="video-container">
                                                <iframe width="100%" height="30vh" src="{{ "https://www.youtube.com/embed/"~video.codeEsp}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                            </div>
                                            <div class="text-primary description-video m-t-2  text-center">
                                                {{ app.request.locale == 'es' ? video.descriptionEsp|raw: video.descriptionEng|raw }}
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="row slider-controls m-b-5 a-opacity " id="blog-4">
                                    <div class="col-24 text-center text-lg-start d-flex justify-content-center align-items-center">
                                        <div class="">
                                            <img class="slider-testimony-prev me-4" src="{{ asset('build/images/template/prev-v.svg') }}" alt="Anterior" title="Anterior">
                                            <img class="slider-testimony-next" src="{{ asset('build/images/template/next-v.svg') }}" alt="Siguiente" title="Siguiente">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-24 text-center d-md-flex align-items-center justify-content-center sound m-b-3 m-t-10 m-md-t-3 a-opacity a-b-4">
                                <h5 class="text-primary">{% trans %} Escuchalos también como podcasts en:{% endtrans %}</h5>
                                <a href="https://podcasts.apple.com/mx/podcast/un-caf%C3%A9-con-scala/id1559656116" target="_blank" class="m-l-1" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Apple'});">
                                    <img src="{{ asset('build/images/template/apple.svg') }}" alt="" class="img-fluid"/>
                                </a>
                                <a href="https://open.spotify.com/show/5aBjupDK3LqCYmlCEvkBNz" target="_blank" onclick="gtag('event', 'Ir a Podcast', {'event_category': 'Podcasts', 'event_label': 'Spotify'});">
                                    <img src="{{ asset('build/images/template/spotify.svg') }}" alt="" class="img-fluid"/>
                                </a>

                                </iv>
                            </div>
                            <div class="col-md-8 mx-auto m-b-10 text-center a-opacity a-b-4">
                                <a class=" btn btn-primary btn-more-video" href="{{ path("coffee")}}">{% trans %}Ver más un Café con Scala{% endtrans %}</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <section class="wrap-book">
                <div class="row bg-dark">
                    <div class="col">
                        <div class="container ">
                            <div class="row bg-play">
                                <div class="col-md-9 col-20 mx-auto m-t-10">
                                    <img src="{{ asset('build/images/template/logo-play-book.svg') }}" alt="" class="img-fluid"/>
                                </div>
                                <div class="col-md-18 col-20 mx-auto m-md-t-3 m-md-b-5 m-t-7 m-b-7">
                                    <p class="text-white text-md-center ">
                                        {% trans %}
                                        Conozca de la mano de cada uno de nuestros ejecutivos los procesos y acciones que realizamos 
                                        y los objetivos que se persiguen en cada una de las fases del Modelo ScalaHed.
                                        {% endtrans %}
                                    </p>
                                </div>
                                <div class="container">

                                    <section class=" row cont-element slider-play">
                                        {% for video in playBook %}
                                            <div class="col-md-12   m-t-2">
                                                <a class=" pl-0 m-y-1 " data-fancybox data-type="iframe" data-src="{{ video.url}}" href="javascript:;" onclick="gtag('event', 'Ir a Playbook', {'event_category': 'Playbooks', 'event_label': '{{video.nombreEsp}}'});">
                                                    <div class="position-relative element">
                                                        <img src="{{ vich_uploader_asset(video, 'imageFile')}}" class='img-fluid h-100 '/>
                                                    </div>
                                                </a>
                                            </div>
                                        {% endfor %}
                                    </section>
                                    <div class="row slider-controls m-b-5 a-opacity d-md-none m-t-2">
                                        <div class="col-24 text-center text-lg-start d-flex justify-content-center align-items-center">
                                            <div class="">
                                                <img class="slider-play-prev me-4" src="{{ asset('build/images/template/slaider-l.svg') }}" alt="Anterior" title="Anterior">
                                                <img class="slider-play-next" src="{{ asset('build/images/template/slaider-r.svg') }}" alt="Siguiente" title="Siguiente">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row m-md-t-7 m-t-15 m-b-5 ">
                                        <div class="col-md-24 mx-auto m-y-3 cont-scrool">
                                            <div class="cont-mb d-flex">
                                                <div class="col-md-7 d-flex align-items-center">
                                                    <img src="{{ asset('build/images/template/a.png') }}" alt="" class="img-fluid"/>
                                                </div>
                                                <div class="col-md-10">
                                                    <img src="{{ asset('build/images/template/b.png') }}" alt="" class="img-fluid"/>
                                                </div>
                                                <div class="col-md-7 d-flex align-items-center">
                                                    <img src="{{ asset('build/images/template/c.png') }}" alt="" class="img-fluid"/>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </section>

{% endblock %}

templates/blog/play.html.twig
{% extends 'base.html.twig' %}

{% block title %}<title>Scalahed - Higher Education</title>{% endblock %}

{% block body %}
    <div class="row m-t-15">
        <div class="col-md-14 mx-auto m-y-10">
             <div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;"><iframe style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden" frameborder="0" type="text/html" src="{{video.url}}" width="100%" height="100%"   allow="autoplay" allowfullscreen></iframe></div>
        </div>
    </div>

{% endblock %}