src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TeamRepository::class)
 * @Vich\Uploadable
 */
class Team
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description_eng;

    /**
     * @ORM\Column(type="text")
     */
    private $description_esp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $position;
    
    
     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="new_images", fileNameProperty="photo")
     * @var File
     */
    private $photoFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $positionEng;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;
    
    
    
     /**
     * @return mixed
     */
    public function getPhotoFile()
    {
        return $this->photoFile;
    }

    /**
     * @param mixed $imageFile
     */
    public function setPhotoFile($photoFile): void
    {
        $this->photoFile = $photoFile;

        if ($photoFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    public function getPhoto()
    {
        return $this->photo;
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescriptionEng(): ?string
    {
        return $this->description_eng;
    }

    public function setDescriptionEng(string $description_eng): self
    {
        $this->description_eng = $description_eng;

        return $this;
    }

    public function getDescriptionEsp(): ?string
    {
        return $this->description_esp;
    }

    public function setDescriptionEsp(string $description_esp): self
    {
        $this->description_esp = $description_esp;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPositionEng(): ?string
    {
        return $this->positionEng;
    }

    public function setPositionEng(?string $positionEng): self
    {
        $this->positionEng = $positionEng;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }
}

src/Controller/AboutUsController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class AboutUsController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(string $name = null, EntityManagerInterface $entityManager) {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/sobre-nosotros", name="about_us")
     */
    public function index(): Response
    {
        $team = $this->entityManager->getRepository(Team::class)->findBy(array(), array('last_name' => 'ASC'));

        return $this->render('about_us/index.html.twig', [
            'controller_name' => 'AboutUsController',
            'team' => $team
        ]);
    }
}

templates/about_us/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AboutUsController!{% endblock %}

{% block body %}
    <div class="container-fluid about_animate">

        <section class="history m-md-t-7 m-md-t-20 m-t-interior col">
            <div class="container">
                <div class="row start_animation">
                    <div class="col-md-7 offset-md-1 col-22 offset-1 a-transition-l ">
                        <h1 class="text-primary m-md-y-0 m-y-10">
                            {% trans %}
                                Historia
                            {% endtrans %}
                        </h1>
                    </div>
                    <div class="col-md-15 offset-md-1 col-22 offset-1 a-transition-r ">
                        <h4 class="text-primary">
                            {% trans %}
                                Scala Higher Education nació en 2012 gracias a la alianza de Pearson y Grupo Guerra, organizaciones expertas en educación.
                            {% endtrans %}
                        </h4>
                        <h5 class=" m-t-2">
                            {% trans %}
                                Posteriormente, pasó a formar parte de la alianza entre Linzor Capital y Seek Limited.
                            {% endtrans %}
                        </h5>
                    </div>
                </div>
                <div class="row m-t-3 a-a-1" id="about-1">
                    <div class="col-md-5 offset-md-2 col-12 offset-6  d-flex align-items-center align-content-center m-t-md-0 m-t-5">
                        <div class="a-opacity-l">
                            <img src="{{ asset('build/images/about/seek.svg') }}" alt="" class="img-fluid"/>
                            <img src="{{ asset('build/images/about/linzor.svg') }}" alt="" class="img-fluid m-t-3"/>

                        </div>
                    </div>
                    <div class="col-md-15 offset-md-1 m-t-10 m-md-t-0 a-opacity-r">
                        <img src="{{ asset('build/images/about/history.svg') }}" alt="" class="img-fluid"/>
                    </div>
                </div>
                <div class="row m-t-4 container-txt a-a-2" id="about-2">
                    <div class="col-md-10 offset-md-2 col-22 offset-1 line-deco a-opacity-t">
                        <p>
                            {% trans %}
                                <b>Linzor Capital Partners</b> es una firma líder de capital privado que invierte en empresas del área ambiental, social,
                                de gobierno y de crecimiento y sostenibilidad en Latinoamérica.
                                Busca crear valor mediante la implementación de iniciativas estratégicas y mejoras operativas para promover el crecimiento de estas.
                            {% endtrans %}
                        </p>
                    </div>
                    <div class="col-md-10 offset-md-0 col-22 offset-1 a-opacity-t">
                        <p>
                            {% trans %}
                                <b>Seek Limited</b>, cotizante en la bolsa de valores, tiene inversiones en Open University de Inglaterra,
                                Coursera y portales de empleo en diferentes países y continentes, con más de 4.5 millones de usuarios.
                            {% endtrans %}
                        </p>
                    </div>
                </div>
            </div>

        </section>
        <section class="higher-education m-t-5 a-a-3" id="about-3">
            <div class="row bg-secondary position-relative">
                <div class="col">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 m-t-4 a-transition-l">
                                <img src="{{ asset('build/images/about/education.svg') }}" alt="" class="img-fluid"/>
                            </div>
                            <div class="col-md-9 offset-md-1 col-22 offset-1 m-t-5">

                                    <h2 class="text-primary title m-t-10 a-opacity-r ">
                                        {% trans %}
                                            Hoy, Scala Higher Education
                                            es un importante aliado de
                                            la educación superior virtual.
                                        {% endtrans %}
                                    </h2>

                                <section class="a-opacity">
                                    <p class="m-t-5">
                                        {% trans %}
                                            Desde hace doce años acompañamos a las universidades a incursionar en la virtualidad para incrementar el acceso de millones de personas a la educación superior y permanente, en Latinoamérica y el mundo.
                                        {% endtrans %}
                                    </p>
                                    <p class="m-y-5 m-md-y-1">
                                        {% trans %}
                                            Es así como hemos potenciando el crecimiento de estudiantes y universidades en Argentina, Chile, Colombia, Ecuador, México, Perú y muchos otros países.
                                        {% endtrans %}
                                    </p>
                                    <p class="m-b-15 m-md-b-0">
                                        {% trans %}
                                            Actualmente, a través de nuestras alianzas, contamos con más de 45 mil estudiantes activos y 900 profesores en línea. Asimismo, el equipo Scala se conforma de profesionales con amplia experiencia, ubicados en toda Latinoamérica.
                                        {% endtrans %}
                                    </p>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="team m-t-4 ">
            <div class="container a-a-5">
                <div class="row " id="about-4">
                    <div class="col-md-14 offset-md-5 col-22 offset-1 a-a-4">
                        <h2 class="text-primary text-md-center m-b-5 a-opacity-t">
                            {% trans %}
                                Contamos con un equipo con amplia trayectoria internacional
                            {% endtrans %}
                        </h2>
                    </div>
                    <div class="col-24 border-di " id="about-5">
                        <div class="collapse collapse-team">
                            <div class="d-flex flex-column flex-lg-row col-md-24 col-20 mx-auto">
                                <div class="data position-relative">
                                    <img src="{{ asset('build/images/about/team1.svg') }}" alt="" class="img-fluid collapse-team-photo"/>
                                    <a href="#" class="collapse-team-url" target="_blank">
                                        <img class="in-url" src="{{ asset('build/images/template/in-url.svg') }}" alt="in" title="in">
                                    </a>
                                </div>
                                <div class="description d-flex d-lg-block flex-column c mx-auto col-md-18">
                                    <div class="text-center text-lg-end  order-1 m-t-10 m-md-t-0">
                                        <img class="close" src="{{ asset('build/images/template/close.svg') }}" alt="Cerrar" title="Cerrar">
                                    </div>
                                    <div class="data">
                                        <h3 class="text-primary collapse-team-name m-l-10 m-md-l-0">{% trans %}Angela Andrade{% endtrans %}</h3>
                                        <p class="text-dark collapse-team-position m-l-10 m-md-l-0">{% trans %}Directora de Alianzas{% endtrans %}</p>
                                    </div>
                                    <div class="collapse-team-description order-0 m-t-5 mb-10 m-md-t-0 m-md-b-0">

                                        <p>{% trans %}Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequun{% endtrans %}</p>
                                        <p>{% trans %}Non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatu{% endtrans %}</p>
                                        <p>{% trans %}Numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exerc{% endtrans %}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row m-b-5 a-opacity-t">
                    <div class="col-md-24  col-24 position-relative  m-t-3">
                        <img class="slider-team-prev me-4" src="{{ asset('build/images/template/l.jpg') }}" alt="Anterior" title="Anterior">
                        <div class="row  slider-team ">

                            {% for person in team %}

                                <div class=" position-relative">
                                    <a class=" m-t-5 m-md-t-0 collapse-hover {{loop.first ? 'active'}}" data-description="{{ app.request.locale == 'es' ? person.descriptionesp: person.descriptioneng }}" data-url="{{person.url}}" aria-expanded="false">
                                        <img src="{{ vich_uploader_asset(person, 'photoFile') }}" alt="" class="img-fluid team-photo"/>
                                        <h3 class="text-primary team-name m-t-1">
                                            {{person.name}}<br>
                                            {{person.lastName}}
                                        </h3>
                                        <p class="text-dark team-position">
                                            {{ app.request.locale == 'es' ? person.position: person.positionEng }}
                                        </p>
                                    </a>
                                    <a href="{{person.url}}"  target="_blank" class=" in-url" onclick="gtag('event', 'Ir a perfil de LinkedIn', {'event_category': 'LinkedIn Usuarios','event_label': '{{person.name}}'});">
                                        <img class="" src="{{ asset('build/images/template/in-url.svg') }}" alt="in" title="in">
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                        <img class="slider-team-next" src="{{ asset('build/images/template/r.jpg') }}" alt="Siguiente" title="Siguiente">
                    </div>

                </div>

            </div>

        </section>
    </div>
{% endblock %}